//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/Key/KeySetting.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @KeySetting : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @KeySetting()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""KeySetting"",
    ""maps"": [
        {
            ""name"": ""KEY8"",
            ""id"": ""fa0cab59-ccbc-4586-b355-1998dfad7d88"",
            ""actions"": [
                {
                    ""name"": ""Line1"",
                    ""type"": ""Button"",
                    ""id"": ""23f0043c-3302-43d1-bf31-91dc877bdcb9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line2"",
                    ""type"": ""Button"",
                    ""id"": ""539478be-298f-495e-83b4-382bde75eb05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line3"",
                    ""type"": ""Button"",
                    ""id"": ""1eb4be55-10ce-4279-bbab-d4c42885009a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line4"",
                    ""type"": ""Button"",
                    ""id"": ""c810f0e4-a1fe-4a9c-a754-e0ca748bc991"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line5"",
                    ""type"": ""Button"",
                    ""id"": ""d6d4b9c2-f253-4d91-a1f1-ac500d4d32e3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line6"",
                    ""type"": ""Button"",
                    ""id"": ""8e78ce39-edb4-4f9d-9794-2350207d2048"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L_Trig"",
                    ""type"": ""Button"",
                    ""id"": ""3ec6e9cf-ee1f-4b57-9cef-26f730dc2d71"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R_Trig"",
                    ""type"": ""Button"",
                    ""id"": ""89380848-2b05-4836-8a0e-ddcaa08885f2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""93688e57-3e7b-40e5-9896-b382159e86bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3da7ece0-6a48-433e-86d3-0db0c6607b77"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4591977-df57-4d5f-8eb4-2d48126dfe41"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12f35587-1fdb-4f82-b591-720645f1d75d"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""710f26f1-e5f9-4812-aaa0-b00e75271c5b"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8ea15b3-a23b-4a09-8b04-7fcac1318f84"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39169f71-bf4c-42fa-8c27-96a8830747b3"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb167296-8f0e-447d-91a0-a10cc49a4c0b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L_Trig"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cceb49a7-ddf9-4fef-a391-2011e48ef41f"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R_Trig"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""726f712f-4253-46bf-9c51-bcb644dfe327"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MainMenu"",
            ""id"": ""e8cd949f-c12d-437f-a122-7892ea4e02a7"",
            ""actions"": [
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""4e23e6c1-ffcb-4e59-9066-f66f10a2a847"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Arrow"",
                    ""type"": ""Value"",
                    ""id"": ""4ec45645-0371-481d-9155-ffa651a36be9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NoteSpeed"",
                    ""type"": ""Value"",
                    ""id"": ""a5c9ac1c-f39d-4de5-b24f-893f0bff3588"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""bd410073-32c8-41cb-977f-6d30d3924c12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6f89b68d-0834-4820-9da1-96a16395518c"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9e8480d-2a08-416d-8395-f9166a1c47ea"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""ca1c5f40-b1c8-46f7-8153-452da2d43f2e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Arrow"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""dfbf1c4d-d36c-4f53-ac55-7e4f48e64876"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Arrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""7e6425d3-33ff-47f2-9e67-2fa2dd476f33"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Arrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""f21d99db-750e-4083-8318-e9f1afa082e2"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Arrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""bde93558-cf69-4e97-9e1b-1e4636cdf03a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Arrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""41ba516b-69c7-4a01-917f-479398ff5f7f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NoteSpeed"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""0ee869c7-7f28-4f27-bfe7-aa842ff196c8"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NoteSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ecb5cb86-3bda-490b-83d8-82bb132f2224"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NoteSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""04ee830a-f4f2-4fad-b0eb-85e7b7a5a98c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""KEY4"",
            ""id"": ""f16a0edc-abc9-4c55-9bb6-9fb2cad8fffd"",
            ""actions"": [
                {
                    ""name"": ""Line1"",
                    ""type"": ""Button"",
                    ""id"": ""03c538fd-bd66-4b91-bfe2-9735add83f02"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line2"",
                    ""type"": ""Button"",
                    ""id"": ""c2f15ea3-60d3-455f-993c-b62d80c5e24c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line3"",
                    ""type"": ""Button"",
                    ""id"": ""8699ceb5-9647-43c6-930b-f92ea15b52b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line4"",
                    ""type"": ""Button"",
                    ""id"": ""48cfab8b-d36b-493e-9dca-a72c93eb828b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""49e6e73f-aba6-4654-b54c-b534edc0fc56"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""82c1188b-c21f-487d-906a-96257ab2d2b7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e6454b9-b809-4cb9-b5e9-6152bacd3839"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6924508c-b7d3-4b0b-9187-ecbab0e6cff3"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6cde1ef-5b69-495e-90cb-55487ef57773"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3ae09c5-c39f-49b6-9d74-b0e2e56d05b4"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""KEY5"",
            ""id"": ""fec1fe72-bfc7-4968-803e-236d01b5d2a0"",
            ""actions"": [
                {
                    ""name"": ""Line1"",
                    ""type"": ""Button"",
                    ""id"": ""12426489-df0d-4bfe-af35-a36b286b49c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line2"",
                    ""type"": ""Button"",
                    ""id"": ""52e07127-2783-4048-b2c1-b2282b8f5e65"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line3"",
                    ""type"": ""Button"",
                    ""id"": ""685502be-d68c-475f-9fbe-90f910424571"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line4"",
                    ""type"": ""Button"",
                    ""id"": ""16ccb09b-5aba-4d27-bb38-7a3026b69e15"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line5"",
                    ""type"": ""Button"",
                    ""id"": ""a79a5258-15da-4edb-a991-d45f89b5fdf9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""00aeab1d-6f31-4e00-be0b-275e7d0d7383"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""81ed267b-2a2e-4ddc-8cc9-ca86f55ea751"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad4c4579-0e42-460b-91d3-0f50fa7b64d6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54cdf3c2-c5c0-4aa8-b75c-a5b0c8bc6e39"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1ec3429-861f-4ae6-844e-61d2150a9f2c"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4ed91fa-ef33-447d-b9c1-9e509ee3ebe3"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8048bef-1905-414a-83b8-83a51091666d"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3dac3d17-3a61-4332-ac1e-0672f20c7a32"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""KEY6"",
            ""id"": ""871e5282-7202-4587-b0e7-99449baa5d13"",
            ""actions"": [
                {
                    ""name"": ""Line1"",
                    ""type"": ""Button"",
                    ""id"": ""b75a1ea8-6e1a-43c2-9d2f-c9019928d939"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line2"",
                    ""type"": ""Button"",
                    ""id"": ""504b9665-d4f4-4476-b4d9-e8bc0c826cc4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line3"",
                    ""type"": ""Button"",
                    ""id"": ""f087c091-2c86-4ab5-9873-c8d2e6767bce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line4"",
                    ""type"": ""Button"",
                    ""id"": ""c772ab74-e0e0-4b90-8118-f2df3e664cda"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line5"",
                    ""type"": ""Button"",
                    ""id"": ""c25517e4-3d04-4c4e-9512-eb6282c8b1e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line6"",
                    ""type"": ""Button"",
                    ""id"": ""fcd02896-1adb-4247-983b-8dec35f192fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""441304e0-51be-4821-9ac2-a9a042a4beda"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""89c4dae4-c834-4171-85cd-7343ea33c222"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce102467-2c47-467a-ab53-677ada01331e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06b87756-ccdd-4ac7-afad-e7bc3f735977"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63e4e809-9320-44f5-b33e-9b108fa67073"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a09788d-bf13-4a9e-ad4e-f089032ab140"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d97ccec-fa17-4424-81d3-77b7c9d1f3be"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""Line6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0575a93-ab5d-42b1-bedb-45fd383d6d97"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""New control scheme"",
            ""bindingGroup"": ""New control scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // KEY8
        m_KEY8 = asset.FindActionMap("KEY8", throwIfNotFound: true);
        m_KEY8_Line1 = m_KEY8.FindAction("Line1", throwIfNotFound: true);
        m_KEY8_Line2 = m_KEY8.FindAction("Line2", throwIfNotFound: true);
        m_KEY8_Line3 = m_KEY8.FindAction("Line3", throwIfNotFound: true);
        m_KEY8_Line4 = m_KEY8.FindAction("Line4", throwIfNotFound: true);
        m_KEY8_Line5 = m_KEY8.FindAction("Line5", throwIfNotFound: true);
        m_KEY8_Line6 = m_KEY8.FindAction("Line6", throwIfNotFound: true);
        m_KEY8_L_Trig = m_KEY8.FindAction("L_Trig", throwIfNotFound: true);
        m_KEY8_R_Trig = m_KEY8.FindAction("R_Trig", throwIfNotFound: true);
        m_KEY8_Escape = m_KEY8.FindAction("Escape", throwIfNotFound: true);
        // MainMenu
        m_MainMenu = asset.FindActionMap("MainMenu", throwIfNotFound: true);
        m_MainMenu_Submit = m_MainMenu.FindAction("Submit", throwIfNotFound: true);
        m_MainMenu_Arrow = m_MainMenu.FindAction("Arrow", throwIfNotFound: true);
        m_MainMenu_NoteSpeed = m_MainMenu.FindAction("NoteSpeed", throwIfNotFound: true);
        m_MainMenu_Back = m_MainMenu.FindAction("Back", throwIfNotFound: true);
        // KEY4
        m_KEY4 = asset.FindActionMap("KEY4", throwIfNotFound: true);
        m_KEY4_Line1 = m_KEY4.FindAction("Line1", throwIfNotFound: true);
        m_KEY4_Line2 = m_KEY4.FindAction("Line2", throwIfNotFound: true);
        m_KEY4_Line3 = m_KEY4.FindAction("Line3", throwIfNotFound: true);
        m_KEY4_Line4 = m_KEY4.FindAction("Line4", throwIfNotFound: true);
        m_KEY4_Escape = m_KEY4.FindAction("Escape", throwIfNotFound: true);
        // KEY5
        m_KEY5 = asset.FindActionMap("KEY5", throwIfNotFound: true);
        m_KEY5_Line1 = m_KEY5.FindAction("Line1", throwIfNotFound: true);
        m_KEY5_Line2 = m_KEY5.FindAction("Line2", throwIfNotFound: true);
        m_KEY5_Line3 = m_KEY5.FindAction("Line3", throwIfNotFound: true);
        m_KEY5_Line4 = m_KEY5.FindAction("Line4", throwIfNotFound: true);
        m_KEY5_Line5 = m_KEY5.FindAction("Line5", throwIfNotFound: true);
        m_KEY5_Escape = m_KEY5.FindAction("Escape", throwIfNotFound: true);
        // KEY6
        m_KEY6 = asset.FindActionMap("KEY6", throwIfNotFound: true);
        m_KEY6_Line1 = m_KEY6.FindAction("Line1", throwIfNotFound: true);
        m_KEY6_Line2 = m_KEY6.FindAction("Line2", throwIfNotFound: true);
        m_KEY6_Line3 = m_KEY6.FindAction("Line3", throwIfNotFound: true);
        m_KEY6_Line4 = m_KEY6.FindAction("Line4", throwIfNotFound: true);
        m_KEY6_Line5 = m_KEY6.FindAction("Line5", throwIfNotFound: true);
        m_KEY6_Line6 = m_KEY6.FindAction("Line6", throwIfNotFound: true);
        m_KEY6_Escape = m_KEY6.FindAction("Escape", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // KEY8
    private readonly InputActionMap m_KEY8;
    private IKEY8Actions m_KEY8ActionsCallbackInterface;
    private readonly InputAction m_KEY8_Line1;
    private readonly InputAction m_KEY8_Line2;
    private readonly InputAction m_KEY8_Line3;
    private readonly InputAction m_KEY8_Line4;
    private readonly InputAction m_KEY8_Line5;
    private readonly InputAction m_KEY8_Line6;
    private readonly InputAction m_KEY8_L_Trig;
    private readonly InputAction m_KEY8_R_Trig;
    private readonly InputAction m_KEY8_Escape;
    public struct KEY8Actions
    {
        private @KeySetting m_Wrapper;
        public KEY8Actions(@KeySetting wrapper) { m_Wrapper = wrapper; }
        public InputAction @Line1 => m_Wrapper.m_KEY8_Line1;
        public InputAction @Line2 => m_Wrapper.m_KEY8_Line2;
        public InputAction @Line3 => m_Wrapper.m_KEY8_Line3;
        public InputAction @Line4 => m_Wrapper.m_KEY8_Line4;
        public InputAction @Line5 => m_Wrapper.m_KEY8_Line5;
        public InputAction @Line6 => m_Wrapper.m_KEY8_Line6;
        public InputAction @L_Trig => m_Wrapper.m_KEY8_L_Trig;
        public InputAction @R_Trig => m_Wrapper.m_KEY8_R_Trig;
        public InputAction @Escape => m_Wrapper.m_KEY8_Escape;
        public InputActionMap Get() { return m_Wrapper.m_KEY8; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KEY8Actions set) { return set.Get(); }
        public void SetCallbacks(IKEY8Actions instance)
        {
            if (m_Wrapper.m_KEY8ActionsCallbackInterface != null)
            {
                @Line1.started -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnLine1;
                @Line1.performed -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnLine1;
                @Line1.canceled -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnLine1;
                @Line2.started -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnLine2;
                @Line2.performed -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnLine2;
                @Line2.canceled -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnLine2;
                @Line3.started -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnLine3;
                @Line3.performed -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnLine3;
                @Line3.canceled -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnLine3;
                @Line4.started -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnLine4;
                @Line4.performed -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnLine4;
                @Line4.canceled -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnLine4;
                @Line5.started -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnLine5;
                @Line5.performed -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnLine5;
                @Line5.canceled -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnLine5;
                @Line6.started -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnLine6;
                @Line6.performed -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnLine6;
                @Line6.canceled -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnLine6;
                @L_Trig.started -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnL_Trig;
                @L_Trig.performed -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnL_Trig;
                @L_Trig.canceled -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnL_Trig;
                @R_Trig.started -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnR_Trig;
                @R_Trig.performed -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnR_Trig;
                @R_Trig.canceled -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnR_Trig;
                @Escape.started -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnEscape;
                @Escape.performed -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnEscape;
                @Escape.canceled -= m_Wrapper.m_KEY8ActionsCallbackInterface.OnEscape;
            }
            m_Wrapper.m_KEY8ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Line1.started += instance.OnLine1;
                @Line1.performed += instance.OnLine1;
                @Line1.canceled += instance.OnLine1;
                @Line2.started += instance.OnLine2;
                @Line2.performed += instance.OnLine2;
                @Line2.canceled += instance.OnLine2;
                @Line3.started += instance.OnLine3;
                @Line3.performed += instance.OnLine3;
                @Line3.canceled += instance.OnLine3;
                @Line4.started += instance.OnLine4;
                @Line4.performed += instance.OnLine4;
                @Line4.canceled += instance.OnLine4;
                @Line5.started += instance.OnLine5;
                @Line5.performed += instance.OnLine5;
                @Line5.canceled += instance.OnLine5;
                @Line6.started += instance.OnLine6;
                @Line6.performed += instance.OnLine6;
                @Line6.canceled += instance.OnLine6;
                @L_Trig.started += instance.OnL_Trig;
                @L_Trig.performed += instance.OnL_Trig;
                @L_Trig.canceled += instance.OnL_Trig;
                @R_Trig.started += instance.OnR_Trig;
                @R_Trig.performed += instance.OnR_Trig;
                @R_Trig.canceled += instance.OnR_Trig;
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
            }
        }
    }
    public KEY8Actions @KEY8 => new KEY8Actions(this);

    // MainMenu
    private readonly InputActionMap m_MainMenu;
    private IMainMenuActions m_MainMenuActionsCallbackInterface;
    private readonly InputAction m_MainMenu_Submit;
    private readonly InputAction m_MainMenu_Arrow;
    private readonly InputAction m_MainMenu_NoteSpeed;
    private readonly InputAction m_MainMenu_Back;
    public struct MainMenuActions
    {
        private @KeySetting m_Wrapper;
        public MainMenuActions(@KeySetting wrapper) { m_Wrapper = wrapper; }
        public InputAction @Submit => m_Wrapper.m_MainMenu_Submit;
        public InputAction @Arrow => m_Wrapper.m_MainMenu_Arrow;
        public InputAction @NoteSpeed => m_Wrapper.m_MainMenu_NoteSpeed;
        public InputAction @Back => m_Wrapper.m_MainMenu_Back;
        public InputActionMap Get() { return m_Wrapper.m_MainMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainMenuActions set) { return set.Get(); }
        public void SetCallbacks(IMainMenuActions instance)
        {
            if (m_Wrapper.m_MainMenuActionsCallbackInterface != null)
            {
                @Submit.started -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnSubmit;
                @Submit.performed -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnSubmit;
                @Submit.canceled -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnSubmit;
                @Arrow.started -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnArrow;
                @Arrow.performed -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnArrow;
                @Arrow.canceled -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnArrow;
                @NoteSpeed.started -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnNoteSpeed;
                @NoteSpeed.performed -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnNoteSpeed;
                @NoteSpeed.canceled -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnNoteSpeed;
                @Back.started -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnBack;
                @Back.performed -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnBack;
                @Back.canceled -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnBack;
            }
            m_Wrapper.m_MainMenuActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
                @Arrow.started += instance.OnArrow;
                @Arrow.performed += instance.OnArrow;
                @Arrow.canceled += instance.OnArrow;
                @NoteSpeed.started += instance.OnNoteSpeed;
                @NoteSpeed.performed += instance.OnNoteSpeed;
                @NoteSpeed.canceled += instance.OnNoteSpeed;
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
            }
        }
    }
    public MainMenuActions @MainMenu => new MainMenuActions(this);

    // KEY4
    private readonly InputActionMap m_KEY4;
    private IKEY4Actions m_KEY4ActionsCallbackInterface;
    private readonly InputAction m_KEY4_Line1;
    private readonly InputAction m_KEY4_Line2;
    private readonly InputAction m_KEY4_Line3;
    private readonly InputAction m_KEY4_Line4;
    private readonly InputAction m_KEY4_Escape;
    public struct KEY4Actions
    {
        private @KeySetting m_Wrapper;
        public KEY4Actions(@KeySetting wrapper) { m_Wrapper = wrapper; }
        public InputAction @Line1 => m_Wrapper.m_KEY4_Line1;
        public InputAction @Line2 => m_Wrapper.m_KEY4_Line2;
        public InputAction @Line3 => m_Wrapper.m_KEY4_Line3;
        public InputAction @Line4 => m_Wrapper.m_KEY4_Line4;
        public InputAction @Escape => m_Wrapper.m_KEY4_Escape;
        public InputActionMap Get() { return m_Wrapper.m_KEY4; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KEY4Actions set) { return set.Get(); }
        public void SetCallbacks(IKEY4Actions instance)
        {
            if (m_Wrapper.m_KEY4ActionsCallbackInterface != null)
            {
                @Line1.started -= m_Wrapper.m_KEY4ActionsCallbackInterface.OnLine1;
                @Line1.performed -= m_Wrapper.m_KEY4ActionsCallbackInterface.OnLine1;
                @Line1.canceled -= m_Wrapper.m_KEY4ActionsCallbackInterface.OnLine1;
                @Line2.started -= m_Wrapper.m_KEY4ActionsCallbackInterface.OnLine2;
                @Line2.performed -= m_Wrapper.m_KEY4ActionsCallbackInterface.OnLine2;
                @Line2.canceled -= m_Wrapper.m_KEY4ActionsCallbackInterface.OnLine2;
                @Line3.started -= m_Wrapper.m_KEY4ActionsCallbackInterface.OnLine3;
                @Line3.performed -= m_Wrapper.m_KEY4ActionsCallbackInterface.OnLine3;
                @Line3.canceled -= m_Wrapper.m_KEY4ActionsCallbackInterface.OnLine3;
                @Line4.started -= m_Wrapper.m_KEY4ActionsCallbackInterface.OnLine4;
                @Line4.performed -= m_Wrapper.m_KEY4ActionsCallbackInterface.OnLine4;
                @Line4.canceled -= m_Wrapper.m_KEY4ActionsCallbackInterface.OnLine4;
                @Escape.started -= m_Wrapper.m_KEY4ActionsCallbackInterface.OnEscape;
                @Escape.performed -= m_Wrapper.m_KEY4ActionsCallbackInterface.OnEscape;
                @Escape.canceled -= m_Wrapper.m_KEY4ActionsCallbackInterface.OnEscape;
            }
            m_Wrapper.m_KEY4ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Line1.started += instance.OnLine1;
                @Line1.performed += instance.OnLine1;
                @Line1.canceled += instance.OnLine1;
                @Line2.started += instance.OnLine2;
                @Line2.performed += instance.OnLine2;
                @Line2.canceled += instance.OnLine2;
                @Line3.started += instance.OnLine3;
                @Line3.performed += instance.OnLine3;
                @Line3.canceled += instance.OnLine3;
                @Line4.started += instance.OnLine4;
                @Line4.performed += instance.OnLine4;
                @Line4.canceled += instance.OnLine4;
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
            }
        }
    }
    public KEY4Actions @KEY4 => new KEY4Actions(this);

    // KEY5
    private readonly InputActionMap m_KEY5;
    private IKEY5Actions m_KEY5ActionsCallbackInterface;
    private readonly InputAction m_KEY5_Line1;
    private readonly InputAction m_KEY5_Line2;
    private readonly InputAction m_KEY5_Line3;
    private readonly InputAction m_KEY5_Line4;
    private readonly InputAction m_KEY5_Line5;
    private readonly InputAction m_KEY5_Escape;
    public struct KEY5Actions
    {
        private @KeySetting m_Wrapper;
        public KEY5Actions(@KeySetting wrapper) { m_Wrapper = wrapper; }
        public InputAction @Line1 => m_Wrapper.m_KEY5_Line1;
        public InputAction @Line2 => m_Wrapper.m_KEY5_Line2;
        public InputAction @Line3 => m_Wrapper.m_KEY5_Line3;
        public InputAction @Line4 => m_Wrapper.m_KEY5_Line4;
        public InputAction @Line5 => m_Wrapper.m_KEY5_Line5;
        public InputAction @Escape => m_Wrapper.m_KEY5_Escape;
        public InputActionMap Get() { return m_Wrapper.m_KEY5; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KEY5Actions set) { return set.Get(); }
        public void SetCallbacks(IKEY5Actions instance)
        {
            if (m_Wrapper.m_KEY5ActionsCallbackInterface != null)
            {
                @Line1.started -= m_Wrapper.m_KEY5ActionsCallbackInterface.OnLine1;
                @Line1.performed -= m_Wrapper.m_KEY5ActionsCallbackInterface.OnLine1;
                @Line1.canceled -= m_Wrapper.m_KEY5ActionsCallbackInterface.OnLine1;
                @Line2.started -= m_Wrapper.m_KEY5ActionsCallbackInterface.OnLine2;
                @Line2.performed -= m_Wrapper.m_KEY5ActionsCallbackInterface.OnLine2;
                @Line2.canceled -= m_Wrapper.m_KEY5ActionsCallbackInterface.OnLine2;
                @Line3.started -= m_Wrapper.m_KEY5ActionsCallbackInterface.OnLine3;
                @Line3.performed -= m_Wrapper.m_KEY5ActionsCallbackInterface.OnLine3;
                @Line3.canceled -= m_Wrapper.m_KEY5ActionsCallbackInterface.OnLine3;
                @Line4.started -= m_Wrapper.m_KEY5ActionsCallbackInterface.OnLine4;
                @Line4.performed -= m_Wrapper.m_KEY5ActionsCallbackInterface.OnLine4;
                @Line4.canceled -= m_Wrapper.m_KEY5ActionsCallbackInterface.OnLine4;
                @Line5.started -= m_Wrapper.m_KEY5ActionsCallbackInterface.OnLine5;
                @Line5.performed -= m_Wrapper.m_KEY5ActionsCallbackInterface.OnLine5;
                @Line5.canceled -= m_Wrapper.m_KEY5ActionsCallbackInterface.OnLine5;
                @Escape.started -= m_Wrapper.m_KEY5ActionsCallbackInterface.OnEscape;
                @Escape.performed -= m_Wrapper.m_KEY5ActionsCallbackInterface.OnEscape;
                @Escape.canceled -= m_Wrapper.m_KEY5ActionsCallbackInterface.OnEscape;
            }
            m_Wrapper.m_KEY5ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Line1.started += instance.OnLine1;
                @Line1.performed += instance.OnLine1;
                @Line1.canceled += instance.OnLine1;
                @Line2.started += instance.OnLine2;
                @Line2.performed += instance.OnLine2;
                @Line2.canceled += instance.OnLine2;
                @Line3.started += instance.OnLine3;
                @Line3.performed += instance.OnLine3;
                @Line3.canceled += instance.OnLine3;
                @Line4.started += instance.OnLine4;
                @Line4.performed += instance.OnLine4;
                @Line4.canceled += instance.OnLine4;
                @Line5.started += instance.OnLine5;
                @Line5.performed += instance.OnLine5;
                @Line5.canceled += instance.OnLine5;
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
            }
        }
    }
    public KEY5Actions @KEY5 => new KEY5Actions(this);

    // KEY6
    private readonly InputActionMap m_KEY6;
    private IKEY6Actions m_KEY6ActionsCallbackInterface;
    private readonly InputAction m_KEY6_Line1;
    private readonly InputAction m_KEY6_Line2;
    private readonly InputAction m_KEY6_Line3;
    private readonly InputAction m_KEY6_Line4;
    private readonly InputAction m_KEY6_Line5;
    private readonly InputAction m_KEY6_Line6;
    private readonly InputAction m_KEY6_Escape;
    public struct KEY6Actions
    {
        private @KeySetting m_Wrapper;
        public KEY6Actions(@KeySetting wrapper) { m_Wrapper = wrapper; }
        public InputAction @Line1 => m_Wrapper.m_KEY6_Line1;
        public InputAction @Line2 => m_Wrapper.m_KEY6_Line2;
        public InputAction @Line3 => m_Wrapper.m_KEY6_Line3;
        public InputAction @Line4 => m_Wrapper.m_KEY6_Line4;
        public InputAction @Line5 => m_Wrapper.m_KEY6_Line5;
        public InputAction @Line6 => m_Wrapper.m_KEY6_Line6;
        public InputAction @Escape => m_Wrapper.m_KEY6_Escape;
        public InputActionMap Get() { return m_Wrapper.m_KEY6; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KEY6Actions set) { return set.Get(); }
        public void SetCallbacks(IKEY6Actions instance)
        {
            if (m_Wrapper.m_KEY6ActionsCallbackInterface != null)
            {
                @Line1.started -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnLine1;
                @Line1.performed -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnLine1;
                @Line1.canceled -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnLine1;
                @Line2.started -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnLine2;
                @Line2.performed -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnLine2;
                @Line2.canceled -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnLine2;
                @Line3.started -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnLine3;
                @Line3.performed -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnLine3;
                @Line3.canceled -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnLine3;
                @Line4.started -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnLine4;
                @Line4.performed -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnLine4;
                @Line4.canceled -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnLine4;
                @Line5.started -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnLine5;
                @Line5.performed -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnLine5;
                @Line5.canceled -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnLine5;
                @Line6.started -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnLine6;
                @Line6.performed -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnLine6;
                @Line6.canceled -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnLine6;
                @Escape.started -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnEscape;
                @Escape.performed -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnEscape;
                @Escape.canceled -= m_Wrapper.m_KEY6ActionsCallbackInterface.OnEscape;
            }
            m_Wrapper.m_KEY6ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Line1.started += instance.OnLine1;
                @Line1.performed += instance.OnLine1;
                @Line1.canceled += instance.OnLine1;
                @Line2.started += instance.OnLine2;
                @Line2.performed += instance.OnLine2;
                @Line2.canceled += instance.OnLine2;
                @Line3.started += instance.OnLine3;
                @Line3.performed += instance.OnLine3;
                @Line3.canceled += instance.OnLine3;
                @Line4.started += instance.OnLine4;
                @Line4.performed += instance.OnLine4;
                @Line4.canceled += instance.OnLine4;
                @Line5.started += instance.OnLine5;
                @Line5.performed += instance.OnLine5;
                @Line5.canceled += instance.OnLine5;
                @Line6.started += instance.OnLine6;
                @Line6.performed += instance.OnLine6;
                @Line6.canceled += instance.OnLine6;
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
            }
        }
    }
    public KEY6Actions @KEY6 => new KEY6Actions(this);
    private int m_NewcontrolschemeSchemeIndex = -1;
    public InputControlScheme NewcontrolschemeScheme
    {
        get
        {
            if (m_NewcontrolschemeSchemeIndex == -1) m_NewcontrolschemeSchemeIndex = asset.FindControlSchemeIndex("New control scheme");
            return asset.controlSchemes[m_NewcontrolschemeSchemeIndex];
        }
    }
    public interface IKEY8Actions
    {
        void OnLine1(InputAction.CallbackContext context);
        void OnLine2(InputAction.CallbackContext context);
        void OnLine3(InputAction.CallbackContext context);
        void OnLine4(InputAction.CallbackContext context);
        void OnLine5(InputAction.CallbackContext context);
        void OnLine6(InputAction.CallbackContext context);
        void OnL_Trig(InputAction.CallbackContext context);
        void OnR_Trig(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
    }
    public interface IMainMenuActions
    {
        void OnSubmit(InputAction.CallbackContext context);
        void OnArrow(InputAction.CallbackContext context);
        void OnNoteSpeed(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
    }
    public interface IKEY4Actions
    {
        void OnLine1(InputAction.CallbackContext context);
        void OnLine2(InputAction.CallbackContext context);
        void OnLine3(InputAction.CallbackContext context);
        void OnLine4(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
    }
    public interface IKEY5Actions
    {
        void OnLine1(InputAction.CallbackContext context);
        void OnLine2(InputAction.CallbackContext context);
        void OnLine3(InputAction.CallbackContext context);
        void OnLine4(InputAction.CallbackContext context);
        void OnLine5(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
    }
    public interface IKEY6Actions
    {
        void OnLine1(InputAction.CallbackContext context);
        void OnLine2(InputAction.CallbackContext context);
        void OnLine3(InputAction.CallbackContext context);
        void OnLine4(InputAction.CallbackContext context);
        void OnLine5(InputAction.CallbackContext context);
        void OnLine6(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
    }
}
